version: "3.9"
services:
  web_api:
    image: carrefour-image
    container_name: web_api_application
    ports:
      - "8080:80"
    depends_on:
      - mssql2019

  mssql2019:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql2019
    ports:
      - "1450:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Pa55w0rd#2022